import test from 'node:test'; import assert from 'node:assert/strict';
import { migrateBToC, normaliseCState, serialiseCState, deleteDocumentFromState, deleteWorkspace, addWorkspace } from '../src/workspaces/workspaceSchema.mjs';
import { createDocument, addSection, updateSection, moveSection, createNamedSnapshot, compareRevisions, restoreRevisionNonDestructive, appendVisibleChatMessage, placeVisibleChatMessage, applyAiDocumentOperation, markDocumentSaveFailed, markDocumentSaved, markDocumentSaving } from '../src/documents/documentDomain.mjs';
import { renderDocumentHtml, renderDocumentMarkdown, renderDocumentText } from '../src/documents/documentRender.mjs';
import { rawZipPreflight } from '../src/utils/rawZipPreflight.mjs';
import { createOrdinaryBackup, prepareAtomicRestore, commitPreparedRestore } from '../src/backup/backupService.mjs';
import { documentProjectPayload, mergeParsedDocumentProjectArchive } from '../src/documents/documentProjectArchive.mjs';
import { projectArchivePayload, mergeParsedProjectArchive } from '../src/export/projectArchive.mjs';
import { classifyLayout, backResolutionOrder } from '../src/ui/responsive.mjs'; import { generationPresentation } from '../src/domain/generationPresentation.mjs';

const base=()=>migrateBToC({chats:[{id:'c1',title:'Chat',messages:[{role:'user',content:'visible'}]}],activeChatId:'c1'},100);
test('v3 to v4 migration is deterministic/idempotent and creates document collections',()=>{const v3={...base(),storageSchemaVersion:3,documents:undefined,documentRevisions:undefined};const v4=migrateBToC(v3,200);const again=normaliseCState(v4,300);assert.equal(v4.storageSchemaVersion,4);assert.deepEqual(again.documents,[]);assert.deepEqual(again.documentRevisions,[]);});

test('document delete removes revisions and workspace relationships without corrupting active selection',()=>{let s=base();const d=createDocument({workspaceId:'workspace-default',title:'Delete me',now:1});const snap=createNamedSnapshot(d,[],'Before delete',2);s=normaliseCState({...s,documents:[snap.document],documentRevisions:snap.revisions,activeDocumentId:snap.document.id});const deleted=deleteDocumentFromState(s,snap.document.id);assert.equal(deleted.documents.length,0);assert.equal(deleted.documentRevisions.length,0);assert.equal(deleted.activeDocumentId,null);assert.equal(deleted.workspaces[0].documentIds.includes(snap.document.id),false);});
test('chat-to-document placement supports before after replace and append targets',()=>{const baseDoc=createDocument({title:'Target',now:1});const first=baseDoc.sections[0];let d=placeVisibleChatMessage(baseDoc,{content:'BEFORE'},{mode:'before',sectionId:first.id,now:2});assert.equal(d.sections[0].content,'BEFORE');d=placeVisibleChatMessage(d,{content:'AFTER'},{mode:'after',sectionId:first.id,now:3});const firstIndex=d.sections.findIndex((section)=>section.id===first.id);assert.equal(d.sections[firstIndex+1].content,'AFTER');d=placeVisibleChatMessage(d,{content:'REPLACED'},{mode:'replace',sectionId:first.id,now:4});assert.equal(d.sections.find((section)=>section.id===first.id).content,'REPLACED');d=placeVisibleChatMessage(d,{content:'APPENDED'},{mode:'append',now:5});assert.equal(d.sections.at(-1).content,'APPENDED');});
test('local durable state retains protected project AI configuration while ordinary backup excludes it',()=>{const s=normaliseCState({...base(),workspaces:[{...base().workspaces[0],projectAIConfiguration:{systemInstructions:'PRIVATE PROJECT INSTRUCTION'}}]});const persisted=serialiseCState(s,10);assert.equal(persisted.workspaces[0].projectAIConfiguration.systemInstructions,'PRIVATE PROJECT INSTRUCTION');const backup=createOrdinaryBackup(s,11);assert.equal(JSON.stringify(backup).includes('PRIVATE PROJECT INSTRUCTION'),false);assert.equal(Object.hasOwn(backup.payload.workspaces[0],'projectAIConfiguration'),false);});
test('multiple documents stay scoped to workspaces and workspace delete preserves documents',()=>{let s=base();s=addWorkspace(s,{name:'Research'},201);const wid=s.activeWorkspaceId;const d=createDocument({workspaceId:wid,title:'Spec'},202);s=normaliseCState({...s,documents:[d]});s=deleteWorkspace(s,wid);assert.equal(s.documents.length,1);assert.equal(s.documents[0].workspaceId,s.activeWorkspaceId);});
test('structured editing and accessible reorder domain operations are deterministic',()=>{let d=createDocument({title:'Doc'});d=addSection(d,{type:'HEADING',content:'H'},null,2);d=updateSection(d,d.sections[0].id,{content:'Body'},3);d=moveSection(d,d.sections[1].id,'up',4);assert.equal(d.sections[0].type,'HEADING');assert.equal(d.sections[1].content,'Body');});
test('snapshots compare and restore non-destructively with checkpoint',()=>{let d=createDocument({title:'A',now:1});let out=createNamedSnapshot(d,[],'First',2);d=updateSection(out.document,out.document.sections[0].id,{content:'changed'},3);const out2=createNamedSnapshot(d,out.revisions,'Second',4);const cmp=compareRevisions(out.revision,out2.revision);assert.equal(cmp.changedSections,1);const restored=restoreRevisionNonDestructive(out2.document,out2.revisions,out.revision.id,5);assert.equal(restored.checkpoint.kind,'RESTORE_CHECKPOINT');assert.equal(restored.document.sections[0].content,'');});
test('chat-to-document and AI operations consume visible text only',()=>{let d=createDocument();d=appendVisibleChatMessage(d,{content:'VISIBLE',apiContent:'SECRET'},2);d=applyAiDocumentOperation(d,{operation:'append',text:'AI VISIBLE',now:3});const serial=JSON.stringify(d);assert.match(serial,/VISIBLE/);assert.equal(serial.includes('SECRET'),false);});
test('render serializers expose composition without hidden metadata',()=>{let d=createDocument({title:'Render'});d={...d,metadata:{apiKey:'secret',subject:'safe'},composition:{...d.composition,header:'Header',footer:'Footer',pageNumbers:true,tableOfContents:true,coverPage:true}};for(const value of [renderDocumentHtml(d),renderDocumentMarkdown(d),renderDocumentText(d)]){assert.equal(value.includes('secret'),false);assert.match(value,/Render/);}assert.match(renderDocumentHtml(d),/page-number/);});
function zipBytes(names){const parts=[];for(const name of names){const b=Buffer.from(name);const h=Buffer.alloc(46);h.writeUInt32LE(0x02014b50,0);h.writeUInt16LE(b.length,28);parts.push(h,b);}return new Uint8Array(Buffer.concat(parts));}
test('raw ZIP preflight detects raw/normalised duplicates and traversal before JSZip',()=>{assert.throws(()=>rawZipPreflight(zipBytes(['a.txt','a.txt'])),/Duplicate raw/);assert.throws(()=>rawZipPreflight(zipBytes(['a/../b.txt'])),/Unsafe ZIP path/);assert.throws(()=>rawZipPreflight(zipBytes(['a\\b.txt','a/b.txt'])),/Duplicate normalised/);});
test('transactional restore verifies durable commit and verified rollback',async()=>{const current=base();const backup=createOrdinaryBackup(current,10);const prepared=prepareAtomicRestore(current,backup,11);let durable=current;let result=await commitPreparedRestore(prepared,{writeState:async s=>(durable=s,true),readState:async()=>durable});assert.equal(result.ok,true);let reads=0;result=await commitPreparedRestore(prepared,{writeState:async s=>(durable=s,true),readState:async()=>{reads++;return reads===1?{...durable,chats:[]}:durable;}});assert.equal(result.ok,false);assert.equal(result.rolledBack,true);});
test('autosave status transitions remain explicit and serialisation excludes hidden context',()=>{let d=createDocument();d=markDocumentSaving(d);assert.equal(d.autosaveStatus,'SAVING');d=markDocumentSaved(d);assert.equal(d.autosaveStatus,'SAVED');d=markDocumentSaveFailed(d);assert.equal(d.autosaveStatus,'SAVE_FAILED');const s=serialiseCState({...base(),documents:[{...d,metadata:{apiKey:'bad',subject:'safe'}}]});assert.equal(Object.hasOwn(s.documents[0].metadata,'apiKey'),false);});
test('document project import remaps document/revision lineage',()=>{const d=createDocument({title:'Portable'});const snap=createNamedSnapshot(d,[],'S',2);const payload=documentProjectPayload(snap.document,snap.revisions);const merged=mergeParsedDocumentProjectArchive(base(),payload,'workspace-default',20);assert.notEqual(merged.documents[0].id,d.id);assert.equal(merged.documentRevisions[0].documentId,merged.documents[0].id);});
test('workspace project merge remaps document revision lineage',()=>{const d=createDocument({workspaceId:'workspace-default',title:'P'});const snap=createNamedSnapshot(d,[],'S',2);const state={...base(),documents:[snap.document],documentRevisions:snap.revisions};const payload=projectArchivePayload(state,'workspace-default');const parsed={...payload,manifest:{}};const merged=mergeParsedProjectArchive(base(),parsed,30);const imported=merged.documents[0];assert.equal(merged.documentRevisions[0].documentId,imported.id);});
test('workspace and document payloads sanitise document/revision metadata',()=>{const d={...createDocument({workspaceId:'workspace-default'}),metadata:{apiKey:'bad',safe:'yes'}};const snap=createNamedSnapshot(d,[],'S',2);const state={...base(),documents:[snap.document],documentRevisions:[{...snap.revision,metadata:{apiKey:'bad'}}]};const p=projectArchivePayload(state,'workspace-default');const dp=documentProjectPayload(snap.document,state.documentRevisions);assert.equal(JSON.stringify(p).includes('"apiKey"'),false);assert.equal(JSON.stringify(dp).includes('"apiKey"'),false);});
test('responsive classifier, Back order and generation presentation are explicit',()=>{assert.equal(classifyLayout(500),'compact');assert.equal(classifyLayout(800),'medium');assert.equal(classifyLayout(1200),'expanded');assert.ok(Array.isArray(backResolutionOrder));assert.match(generationPresentation('FAILED').label,/Failed/i);});
